# Generated by Django 2.2.3 on 2019-07-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappmodel',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
    ]
